export type AgentAuthoringRoute = 'describe' | 'material' | 'manual';
export type AgentScenarioId = 'code' | 'cowork' | 'media';
export type AgentAuthoringField =
  | 'displayName'
  | 'sourceText'
  | 'description'
  | 'prompt'
  | 'scenarios';

export type AgentAuthoringDiagnosticCode =
  | 'display_name_required'
  | 'source_text_required'
  | 'description_required'
  | 'prompt_required'
  | 'scenario_required';

export interface AgentAuthoringDiagnostic {
  code: AgentAuthoringDiagnosticCode;
  field: AgentAuthoringField;
  severity: 'error';
}

export interface AgentAuthoringInput {
  route: AgentAuthoringRoute;
  displayName: string;
  sourceText?: string;
  description?: string;
  prompt?: string;
  scenarios: AgentScenarioId[];
  template?: Partial<AgentAuthoringTemplate>;
}

export interface AgentAuthoringTemplate {
  describeRole: string;
  describeResponsibilities: string;
  describeRequirements: string;
  describeSteps: [string, string, string];
  materialDescriptionPrefix: string;
  materialRole: string;
  materialRules: string;
  materialSteps: [string, string, string];
  materialHeading: string;
}

export interface CanonicalAgentDraft {
  displayName: string;
  description: string;
  prompt: string;
  scenarios: AgentScenarioId[];
  allowedParentAgentIds: string[];
  /** Makes it explicit that this draft was organized locally, not generated by AI. */
  authoringSource: 'deterministic_local';
}

export interface AgentAuthoringResult {
  draft: CanonicalAgentDraft;
  diagnostics: AgentAuthoringDiagnostic[];
  isValid: boolean;
}

export const AGENT_SCENARIO_PARENT_IDS: Readonly<
  Record<AgentScenarioId, readonly string[]>
> = {
  code: ['agentic', 'Plan', 'debug', 'Multitask', 'Team'],
  cowork: ['Cowork', 'DeepResearch', 'Claw'],
  media: ['Media'],
};

const orderedScenarios: AgentScenarioId[] = ['code', 'cowork', 'media'];
const DEFAULT_TEMPLATE: AgentAuthoringTemplate = {
  describeRole: 'You are "__NAME__".',
  describeResponsibilities: 'Your responsibilities:',
  describeRequirements: 'Working requirements:',
  describeSteps: [
    '1. Confirm the goal, available material, and delivery standard first.',
    '2. Work within the defined responsibility and identify missing information explicitly.',
    '3. Return actionable conclusions, steps, or artifacts without fabricating execution results.',
  ],
  materialDescriptionPrefix: 'Execute from imported material:',
  materialRole: 'You are "__NAME__". Use the following material as your working basis.',
  materialRules: 'Working rules:',
  materialSteps: [
    '1. Follow the roles, process, constraints, and output rules in the material.',
    '2. Identify conflicts or gaps before giving the smallest viable recommendation.',
    '3. Never claim that an unperformed tool, file, or external operation was completed.',
  ],
  materialHeading: 'Imported material:',
};

function resolveTemplate(template?: Partial<AgentAuthoringTemplate>): AgentAuthoringTemplate {
  return {
    ...DEFAULT_TEMPLATE,
    ...template,
    describeSteps: template?.describeSteps ?? DEFAULT_TEMPLATE.describeSteps,
    materialSteps: template?.materialSteps ?? DEFAULT_TEMPLATE.materialSteps,
  };
}

function interpolateName(value: string, displayName: string): string {
  return value.split('__NAME__').join(displayName);
}

function normalizeScenarios(scenarios: AgentScenarioId[]): AgentScenarioId[] {
  const selected = new Set(scenarios);
  return orderedScenarios.filter((scenario) => selected.has(scenario));
}

function summarizeSource(sourceText: string): string {
  const compact = sourceText.replace(/\s+/g, ' ').trim();
  if (compact.length <= 72) return compact;
  return `${compact.slice(0, 72)}…`;
}

function createDescribeDraft(
  displayName: string,
  sourceText: string,
  template: AgentAuthoringTemplate,
) {
  const source = sourceText.trim();
  return {
    description: source ? summarizeSource(source) : '',
    prompt: source
      ? [
        interpolateName(template.describeRole, displayName),
        '',
        template.describeResponsibilities,
        source,
        '',
        template.describeRequirements,
        ...template.describeSteps,
      ].join('\n')
      : '',
  };
}

function createMaterialDraft(
  displayName: string,
  sourceText: string,
  template: AgentAuthoringTemplate,
) {
  const source = sourceText.trim();
  return {
    description: source
      ? `${template.materialDescriptionPrefix} ${summarizeSource(source)}`
      : '',
    prompt: source
      ? [
        interpolateName(template.materialRole, displayName),
        '',
        template.materialRules,
        ...template.materialSteps,
        '',
        template.materialHeading,
        source,
      ].join('\n')
      : '',
  };
}

export function organizeAgentDraft(input: AgentAuthoringInput): AgentAuthoringResult {
  const displayName = input.displayName.trim();
  const sourceText = input.sourceText?.trim() ?? '';
  const scenarios = normalizeScenarios(input.scenarios);
  const template = resolveTemplate(input.template);

  let description = input.description?.trim() ?? '';
  let prompt = input.prompt?.trim() ?? '';
  if (input.route === 'describe') {
    ({ description, prompt } = createDescribeDraft(displayName, sourceText, template));
  } else if (input.route === 'material') {
    ({ description, prompt } = createMaterialDraft(displayName, sourceText, template));
  }

  const diagnostics: AgentAuthoringDiagnostic[] = [];
  if (!displayName) {
    diagnostics.push({
      code: 'display_name_required',
      field: 'displayName',
      severity: 'error',
    });
  }
  if (input.route !== 'manual' && !sourceText) {
    diagnostics.push({
      code: 'source_text_required',
      field: 'sourceText',
      severity: 'error',
    });
  }
  if (!description) {
    diagnostics.push({
      code: 'description_required',
      field: 'description',
      severity: 'error',
    });
  }
  if (!prompt) {
    diagnostics.push({
      code: 'prompt_required',
      field: 'prompt',
      severity: 'error',
    });
  }
  if (scenarios.length === 0) {
    diagnostics.push({
      code: 'scenario_required',
      field: 'scenarios',
      severity: 'error',
    });
  }

  const allowedParentAgentIds = Array.from(
    new Set(scenarios.flatMap((scenario) => AGENT_SCENARIO_PARENT_IDS[scenario])),
  ).sort();

  return {
    draft: {
      displayName,
      description,
      prompt,
      scenarios,
      allowedParentAgentIds,
      authoringSource: 'deterministic_local',
    },
    diagnostics,
    isValid: diagnostics.length === 0,
  };
}

export function scenariosFromAllowedParentAgentIds(
  allowedParentAgentIds: readonly string[],
): AgentScenarioId[] {
  if (allowedParentAgentIds.length === 0) {
    return [...orderedScenarios];
  }
  const allowed = new Set(allowedParentAgentIds);
  return orderedScenarios.filter((scenario) =>
    AGENT_SCENARIO_PARENT_IDS[scenario].some((parentId) => allowed.has(parentId)),
  );
}
