import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import test from 'node:test';

const root = process.cwd();
const contractPath = path.join(root, 'src', 'shared', 'i18n', 'contract', 'locales.json');
const sharedTermsDir = path.join(root, 'src', 'shared', 'i18n', 'resources', 'shared');
const expectedGeneratedFiles = [
  'src/web-ui/src/infrastructure/i18n/presets/generatedLocaleContract.ts',
  'src/mobile-web/src/i18n/generatedLocaleContract.ts',
  'Void-Installer/src/i18n/generatedLocaleContract.ts',
  'src/crates/core/src/service/i18n/generated_locale_contract.rs',
  'Void-Installer/src-tauri/src/installer/generated_locale_contract.rs',
  'src/apps/relay-server/static/homepage/i18n.shared.json',
];

function readJson(relativePath) {
  return JSON.parse(fs.readFileSync(path.join(root, relativePath), 'utf8'));
}

function readText(relativePath) {
  return fs.readFileSync(path.join(root, relativePath), 'utf8');
}

function flattenKeys(value, prefix = '') {
  if (value == null || typeof value !== 'object' || Array.isArray(value)) {
    return prefix ? [prefix] : [];
  }

  return Object.entries(value)
    .flatMap(([key, child]) => flattenKeys(child, prefix ? `${prefix}.${key}` : key))
    .sort();
}

function listFiles(dir, predicate) {
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  return entries.flatMap((entry) => {
    const absolutePath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      return listFiles(absolutePath, predicate);
    }

    return predicate(absolutePath) ? [absolutePath] : [];
  });
}

function extractStringArrayConstant(source, exportName) {
  const marker = `export const ${exportName} = [`;
  const start = source.indexOf(marker);
  assert.notEqual(start, -1, `missing ${exportName} constant`);
  const body = source.slice(start + marker.length);
  const end = body.indexOf('] as const');
  assert.notEqual(end, -1, `${exportName} must be an as const string array`);
  return [...body.slice(0, end).matchAll(/'([^']+)'/g)].map((entry) => entry[1]);
}

function extractImportMetaGlobPatterns(source, constantName) {
  const marker = `const ${constantName} = import.meta.glob(`;
  const start = source.indexOf(marker);
  assert.notEqual(start, -1, `missing ${constantName} import.meta.glob`);

  const argumentStart = start + marker.length;
  const remaining = source.slice(argumentStart);
  const leadingWhitespace = remaining.match(/^\s*/)?.[0].length ?? 0;
  const literalStart = argumentStart + leadingWhitespace;

  if (source[literalStart] === "'") {
    const literalEnd = source.indexOf("'", literalStart + 1);
    assert.notEqual(literalEnd, -1, `${constantName} has an unterminated glob literal`);
    return [source.slice(literalStart + 1, literalEnd)];
  }

  assert.equal(source[literalStart], '[', `${constantName} glob patterns must be string literals or a string array`);
  const literalEnd = source.indexOf(']', literalStart + 1);
  assert.notEqual(literalEnd, -1, `${constantName} has an unterminated glob pattern array`);

  const body = source.slice(literalStart + 1, literalEnd);
  const patterns = [...body.matchAll(/'([^']+)'/g)].map((entry) => entry[1]);
  const nonLiteralSource = body.replace(/'[^']+'/g, '').replace(/[\s,]/g, '');
  assert.equal(nonLiteralSource, '', `${constantName} glob patterns must remain literal strings`);
  assert.ok(patterns.length > 0, `${constantName} must contain at least one glob pattern`);
  return patterns;
}

test('i18n contract generated files are in sync with the canonical contract', () => {
  assert.ok(fs.existsSync(contractPath), 'missing shared i18n locale contract');

  const contract = readJson('src/shared/i18n/contract/locales.json');
  assert.deepEqual(
    contract.locales.map((locale) => locale.id),
    ['zh-CN', 'en-US', 'zh-TW'],
  );

  for (const relativePath of expectedGeneratedFiles) {
    const absolutePath = path.join(root, relativePath);
    assert.ok(fs.existsSync(absolutePath), `missing generated contract file: ${relativePath}`);
    if (!relativePath.endsWith('.json')) {
      assert.match(fs.readFileSync(absolutePath, 'utf8'), /generated by scripts\/generate-i18n-contract\.mjs/);
    }
  }

  execFileSync(process.execPath, ['scripts/generate-i18n-contract.mjs', '--check'], {
    cwd: root,
    stdio: 'pipe',
  });
});

test('shared i18n terms exist for every canonical locale with matching keys', () => {
  const contract = readJson('src/shared/i18n/contract/locales.json');
  const expectedLocaleIds = contract.locales.map((locale) => locale.id);

  assert.ok(fs.existsSync(sharedTermsDir), 'missing shared i18n terms directory');

  const baseline = readJson(`src/shared/i18n/resources/shared/${expectedLocaleIds[0]}/terms.json`);
  const baselineKeys = flattenKeys(baseline);

  for (const localeId of expectedLocaleIds) {
    const relativePath = `src/shared/i18n/resources/shared/${localeId}/terms.json`;
    const terms = readJson(relativePath);
    assert.deepEqual(flattenKeys(terms), baselineKeys, `${relativePath} key set differs from baseline`);
  }
});

test('core runtime uses the generated locale contract for language identity', () => {
  const typesSource = readText('src/crates/core/src/service/i18n/types.rs');
  assert.match(
    typesSource,
    /generated_locale_contract::\{[\s\S]*GENERATED_LOCALE_CONTRACT/,
    'LocaleId and LocaleMetadata should derive identity fields from the generated contract',
  );
  assert.doesNotMatch(
    typesSource,
    /locale_registry::\{[\s\S]*(LOCALE_REGISTRY|locale_entry|locale_entry_from_code)/,
    'types.rs must not read language identity from the backend resource registry',
  );

  const resourceRegistrySource = readText('src/crates/core/src/service/i18n/locale_registry.rs');
  assert.doesNotMatch(
    resourceRegistrySource,
    /\b(name|english_name|native_name|rtl|model_language_name|short_model_instruction|aliases):/,
    'backend locale_registry.rs should only own Fluent resource wiring, not duplicate locale identity',
  );
});

test('shared i18n terms are consumed by each product surface runtime', () => {
  const webI18nSource = readText('src/web-ui/src/infrastructure/i18n/core/I18nService.ts');
  assert.match(webI18nSource, /SHARED_TERMS_BY_LOCALE/, 'Web UI should merge shared terms into i18next resources');

  const mobileMessagesSource = readText('src/mobile-web/src/i18n/messages.ts');
  assert.match(mobileMessagesSource, /SHARED_TERMS_BY_LOCALE/, 'mobile-web should expose shared terms through its message tree');

  const installerLanguagesSource = readText('Void-Installer/src/i18n/languages.ts');
  assert.match(installerLanguagesSource, /SHARED_TERMS_BY_APP_LANGUAGE/, 'installer should merge shared terms into its i18next resources');

  const coreServiceSource = readText('src/crates/core/src/service/i18n/service.rs');
  assert.match(coreServiceSource, /generated_shared_term/, 'core i18n service should resolve generated shared terms');
});

test('frontend runtimes use generated locale defaults and fallback chains', () => {
  const webPresetIndexSource = readText('src/web-ui/src/infrastructure/i18n/presets/index.ts');
  assert.doesNotMatch(
    webPresetIndexSource,
    /export const DEFAULT_(?:FALLBACK_)?LOCALE\s*=\s*['"]/,
    'Web UI preset defaults should be re-exported from the generated contract, not hard-coded',
  );

  const webI18nSource = readText('src/web-ui/src/infrastructure/i18n/core/I18nService.ts');
  assert.match(webI18nSource, /getLocaleFallbackChain/, 'Web UI i18next should use the generated locale fallback chain');

  const mobileProviderSource = readText('src/mobile-web/src/i18n/I18nProvider.tsx');
  assert.match(mobileProviderSource, /getMobileFallbackChain/, 'mobile-web translate should use the generated locale fallback chain');
  assert.doesNotMatch(
    mobileProviderSource,
    /messages\[DEFAULT_LANGUAGE\]/,
    'mobile-web translate should not fall back directly to the surface default only',
  );

  const installerI18nSource = readText('Void-Installer/src/i18n/index.ts');
  assert.match(installerI18nSource, /DEFAULT_INSTALLER_UI_LANGUAGE/, 'installer i18next should use the generated default UI language');
  assert.match(installerI18nSource, /getInstallerUiFallbackChain/, 'installer i18next should use the generated locale fallback chain');
});

test('web-ui runtime glob contract keeps only default and fallback bootstrap JSON eager', () => {
  const webI18nSource = readText('src/web-ui/src/infrastructure/i18n/core/I18nService.ts');
  const registrySource = readText('src/web-ui/src/infrastructure/i18n/presets/namespaceRegistry.ts');
  const contract = readJson('src/shared/i18n/contract/locales.json');
  const performanceBudget = readJson('scripts/web-performance-budget.json');
  const bootstrapJsonNamespaces = extractStringArrayConstant(registrySource, 'WEB_UI_BOOTSTRAP_NAMESPACES')
    .filter((namespace) => namespace !== 'shared');
  const eagerLocaleIds = [contract.surfaceDefaults['web-ui'], contract.fallbackLocale];
  const dynamicBootstrapLocaleIds = contract.surfaceOrders['web-ui']
    .filter((localeId) => !eagerLocaleIds.includes(localeId));
  const expectedEagerPatterns = eagerLocaleIds.flatMap((localeId) =>
    bootstrapJsonNamespaces.map((namespace) => `../../../locales/${localeId}/${namespace}.json`));
  const expectedDynamicBootstrapPatterns = dynamicBootstrapLocaleIds.flatMap((localeId) =>
    bootstrapJsonNamespaces.map((namespace) => `../../../locales/${localeId}/${namespace}.json`));
  const expectedDynamicManifestEntries = dynamicBootstrapLocaleIds.flatMap((localeId) =>
    bootstrapJsonNamespaces.map((namespace) => `src/locales/${localeId}/${namespace}.json`));
  const eagerPatterns = extractImportMetaGlobPatterns(webI18nSource, 'bootstrapLocaleModules');
  const lazyPatterns = extractImportMetaGlobPatterns(webI18nSource, 'lazyLocaleModules');
  const lazyPositivePatterns = lazyPatterns.filter((pattern) => !pattern.startsWith('!'));
  const lazyNegativePatterns = lazyPatterns
    .filter((pattern) => pattern.startsWith('!'))
    .map((pattern) => pattern.slice(1));

  assert.match(webI18nSource, /WEB_UI_BOOTSTRAP_NAMESPACES/, 'Web UI should declare the small eager namespace set');
  assert.equal(bootstrapJsonNamespaces.length, 9, 'Web UI should keep exactly nine JSON bootstrap namespaces');
  assert.deepEqual(eagerLocaleIds, ['zh-CN', 'en-US'], 'only the default and global fallback locales should be eager');
  assert.deepEqual(dynamicBootstrapLocaleIds, ['zh-TW'], 'zh-TW bootstrap JSON should remain dynamic');
  assert.deepEqual(
    [...eagerPatterns].sort(),
    [...expectedEagerPatterns].sort(),
    'the eager glob positive set must equal zh-CN/en-US bootstrap JSON exactly',
  );
  assert.deepEqual(
    lazyPositivePatterns,
    ['../../../locales/**/*.json'],
    'the lazy glob should positively include the complete locale JSON tree',
  );
  assert.deepEqual(
    [...lazyNegativePatterns].sort(),
    [...expectedEagerPatterns].sort(),
    'the lazy glob negative set must exclude every eager module exactly once',
  );
  for (const dynamicPattern of expectedDynamicBootstrapPatterns) {
    assert.ok(!lazyNegativePatterns.includes(dynamicPattern), `${dynamicPattern} must remain dynamically importable`);
  }
  assert.deepEqual(
    performanceBudget.requiredDynamicEntries
      .filter((entry) => entry.startsWith('src/locales/'))
      .sort(),
    expectedDynamicManifestEntries.sort(),
    'the performance manifest gate should require all nine zh-TW bootstrap JSON entries',
  );

  const lazyGlobBlock = webI18nSource.match(/const lazyLocaleModules = import\.meta\.glob\([\s\S]*?\) as/)?.[0] ?? '';
  const eagerGlobBlock = webI18nSource.match(/const bootstrapLocaleModules = import\.meta\.glob\([\s\S]*?\) as/)?.[0] ?? '';
  assert.doesNotMatch(
    lazyGlobBlock,
    /eager:\s*true/,
    'Web UI must not eagerly import every locale namespace',
  );
  assert.match(eagerGlobBlock, /eager:\s*true/, 'bootstrap locale modules must remain eager');
});

test('web-ui synchronous i18nService.t namespaces stay in the bootstrap set', () => {
  const registrySource = readText('src/web-ui/src/infrastructure/i18n/presets/namespaceRegistry.ts');
  const bootstrapNamespaces = new Set(extractStringArrayConstant(registrySource, 'WEB_UI_BOOTSTRAP_NAMESPACES'));
  const sourceRoot = path.join(root, 'src', 'web-ui', 'src');
  const missing = new Set();

  const sourceFiles = listFiles(sourceRoot, (file) => {
    const normalized = file.replace(/\\/g, '/');
    return (
      /\.(ts|tsx)$/.test(file) &&
      !normalized.includes('/locales/') &&
      !normalized.endsWith('.test.ts') &&
      !normalized.endsWith('.test.tsx') &&
      !normalized.endsWith('.spec.ts') &&
      !normalized.endsWith('.spec.tsx')
    );
  });

  for (const file of sourceFiles) {
    const text = fs.readFileSync(file, 'utf8');
    const patterns = [/i18nService\.t\(\s*(['"`])([^'"`:]+):/g];
    if (text.includes('i18nService.getT()')) {
      patterns.push(/\bt\(\s*(['"`])([^'"`:]+):/g);
    }

    for (const pattern of patterns) {
      for (const match of text.matchAll(pattern)) {
        const namespace = match[2];
        if (!bootstrapNamespaces.has(namespace)) {
          missing.add(`${namespace} (${path.relative(root, file).replace(/\\/g, '/')})`);
        }
      }
    }
  }

  assert.deepEqual(
    [...missing].sort(),
    [],
    'synchronous i18nService.t(...) call sites require eager bootstrap namespaces',
  );
});

test('i18n audit enforces the checked-in hardcoded source candidate budget', () => {
  const baselineSource = readText('scripts/i18n-hardcoded-baseline.json');
  const auditSource = readText('scripts/i18n-audit.mjs');
  const baseline = JSON.parse(baselineSource);

  assert.doesNotThrow(() => JSON.parse(baselineSource));
  assert.match(auditSource, /i18n-hardcoded-baseline\.json/, 'i18n:audit should read the hardcoded copy baseline');
  assert.match(auditSource, /auditHardcodedSourceBudgets/, 'i18n:audit should fail when hardcoded candidate budgets grow');
  assert.ok(
    baseline.budgets.some((budget) => budget.id === 'web-ui-source' && budget.maxCjkLines === 26),
    'current CJK debt (short-drama services plus the agent-debug protocol marker) should be explicitly budgeted as a no-growth baseline',
  );
  assert.match(auditSource, /--report-json/, 'i18n:audit should expose a machine-readable governance report');
});

test('i18n audit treats locale key parity as an error', () => {
  const auditSource = readText('scripts/i18n-audit.mjs');
  const parityFunction = auditSource.match(/function auditKeyParity\(namespaces\) \{[\s\S]*?\n\}/)?.[0] ?? '';

  assert.match(parityFunction, /reportError\(`\$\{locale\}\/\$\{namespace\}\.json is missing/, 'missing locale keys should fail i18n:audit');
  assert.match(parityFunction, /reportError\(`\$\{locale\}\/\$\{namespace\}\.json has/, 'extra locale keys should fail i18n:audit');
  assert.match(auditSource, /auditMobileWebMessageParity/, 'mobile-web message keys should be covered by i18n:audit');
  assert.match(auditSource, /auditInstallerKeyParity/, 'installer locale keys should be covered by i18n:audit');
});

test('CI runs i18n contract and audit guards before frontend builds', () => {
  const ciSource = readText('.github/workflows/ci.yml');
  const contractIndex = ciSource.indexOf('pnpm run i18n:contract:test');
  const auditIndex = ciSource.indexOf('pnpm run i18n:audit');
  const buildIndex = ciSource.indexOf('pnpm run build:web');

  assert.notEqual(contractIndex, -1, 'CI should run pnpm run i18n:contract:test');
  assert.notEqual(auditIndex, -1, 'CI should run pnpm run i18n:audit');
  assert.ok(contractIndex < buildIndex, 'i18n contract checks should run before web build');
  assert.ok(auditIndex < buildIndex, 'i18n audit should run before web build');
});

test('i18n audit enforces interpolation parameter parity across resource formats', () => {
  const auditSource = readText('scripts/i18n-audit.mjs');

  assert.match(auditSource, /auditWebI18nextPlaceholderParity/, 'Web UI JSON placeholders should be audited');
  assert.match(auditSource, /auditMobileWebPlaceholderParity/, 'mobile-web placeholders should be audited');
  assert.match(auditSource, /auditInstallerPlaceholderParity/, 'installer placeholders should be audited');
  assert.match(auditSource, /auditCoreFluentParity/, 'core Fluent keys and placeholders should be audited');
  assert.match(auditSource, /auditRelayStaticHomepageResources/, 'relay static homepage resources should be audited');
  assert.match(auditSource, /extractI18nextPlaceholders/, 'i18next placeholder extraction should be explicit');
  assert.match(auditSource, /extractMobilePlaceholders/, 'mobile placeholder extraction should be explicit');
  assert.match(auditSource, /extractFluentPlaceholders/, 'Fluent placeholder extraction should be explicit');
});

test('i18n audit fails literal fallbacks and unknown static keys', () => {
  const auditSource = readText('scripts/i18n-audit.mjs');
  const sourceTextAudit = auditSource.match(/function auditSourceText\(\) \{[\s\S]*?\n\}/)?.[0] ?? '';

  assert.match(sourceTextAudit, /reportError/, 'literal t(key, "fallback") candidates should fail audit');
  assert.match(auditSource, /auditWebUiStaticTranslationKeys/, 'static Web UI translation keys should be checked');
  assert.match(auditSource, /collectWebUiStaticTranslationKeys/, 'static key collection should be explicit');
});

test('relay static homepage consumes generated shared terms', () => {
  const generatorSource = readText('scripts/generate-i18n-contract.mjs');
  const relayMessages = readJson('src/apps/relay-server/static/homepage/i18n.json');
  const relayHtml = readText('src/apps/relay-server/static/homepage/index.html');

  assert.match(
    generatorSource,
    /RELAY_HOMEPAGE_SHARED_TERM_KEYS/,
    'generator should declare the relay homepage shared term allowlist',
  );
  assert.deepEqual(
    relayMessages['en-US'].flowMobileSub,
    { $shared: 'features.remoteControl' },
    'relay homepage should reference the shared Remote Control term instead of duplicating it',
  );
  assert.match(
    relayHtml,
    /i18n\.shared\.json/,
    'relay homepage should load generated shared terms',
  );
  assert.match(
    relayHtml,
    /\$shared/,
    'relay homepage should resolve $shared message references at runtime',
  );
});

test('installer Rust locale contract is generated from the installer surface order', () => {
  const generatorSource = readText('scripts/generate-i18n-contract.mjs');
  const installerRustGenerator = generatorSource.match(/function generateInstallerRustLocaleContract\(contract\) \{[\s\S]*?\n\}/)?.[0] ?? '';

  assert.match(installerRustGenerator, /orderedLocales\(contract, 'installer'\)/);
  assert.doesNotMatch(installerRustGenerator, /orderedLocales\(contract, 'core'\)/);
});

test('i18n contract surface resource roots point at existing owned resources', () => {
  const contract = readJson('src/shared/i18n/contract/locales.json');
  const localeById = new Map(contract.locales.map((locale) => [locale.id, locale]));

  for (const [surface, config] of Object.entries(contract.surfaces)) {
    const resourceRoot = path.join(root, config.resourceRoot);
    assert.ok(fs.existsSync(resourceRoot), `${surface} resourceRoot does not exist: ${config.resourceRoot}`);

    for (const localeId of contract.surfaceOrders[surface] ?? []) {
      if (surface === 'web-ui') {
        assert.ok(fs.existsSync(path.join(resourceRoot, localeId)), `${surface} is missing ${localeId} locale directory`);
      } else if (surface === 'installer') {
        const locale = localeById.get(localeId);
        assert.ok(locale?.installer?.uiCode, `${localeId} is missing installer.uiCode`);
        assert.ok(fs.existsSync(path.join(resourceRoot, `${locale.installer.uiCode}.json`)), `${surface} is missing ${localeId} resource JSON`);
      } else if (surface === 'core') {
        assert.ok(fs.existsSync(path.join(resourceRoot, `${localeId}.ftl`)), `${surface} is missing ${localeId} Fluent resource`);
      } else if (surface === 'mobile-web') {
        assert.ok(fs.existsSync(path.join(resourceRoot, 'messages.ts')), `${surface} is missing messages.ts`);
      }
    }
  }
});
