import {
  BookOpen,
  Boxes,
  BrainCircuit,
  Bug,
  Clapperboard,
  ClipboardCheck,
  Code,
  Compass,
  FileText,
  FlaskConical,
  Gauge,
  GitCommit,
  Globe,
  GraduationCap,
  History,
  LayoutGrid,
  ListChecks,
  MessagesSquare,
  MonitorSmartphone,
  Network,
  Package,
  Paintbrush,
  Palette,
  PenLine,
  Presentation,
  Puzzle,
  RefreshCw,
  Replace,
  Rocket,
  Send,
  ShieldCheck,
  Sparkles,
  Table2,
  Telescope,
  TestTube,
  Type,
  WandSparkles,
  Wrench,
  type LucideIcon,
} from 'lucide-react';

const SKILL_ICON_RULES: ReadonlyArray<readonly [RegExp, LucideIcon]> = [
  [/\b(xlsx|spreadsheet|excel|table)\b/i, Table2],
  [/\b(pptx|presentation|slide)\b/i, Presentation],
  [/\b(docx|document|constitution)\b/i, FileText],
  [/\b(officecli|office)\b/i, FileText],
  [/\b(pdf)\b/i, BookOpen],
  [/\b(browser|web|url)\b/i, Globe],
  [/\b(short-drama|storyboard|video|douyin|creator|voice|script)\b/i, Clapperboard],
  [/\b(agent-app|architecture|codebase)\b/i, Network],
  [/\b(adapt|responsive|cross-platform)\b/i, MonitorSmartphone],
  [/\b(arrange|layout|normalize)\b/i, LayoutGrid],
  [/\b(animate|motion)\b/i, WandSparkles],
  [/\b(audit|review|critique|qa|quality)\b/i, ClipboardCheck],
  [/\b(colorize|palette|bolder|quieter)\b/i, Palette],
  [/\b(frontend-design|design-consultation|design-context|teach-impeccable)\b/i, Paintbrush],
  [/\b(clarify|typeset|writing)\b/i, Type],
  [/\b(code-review|diagnose|investigate|triage)\b/i, Bug],
  [/\b(continuous|loop|automation)\b/i, RefreshCw],
  [/\b(grill|office-hours)\b/i, MessagesSquare],
  [/\b(handoff)\b/i, Send],
  [/\b(harden|security)\b/i, ShieldCheck],
  [/\b(migrate|shoehorn)\b/i, Replace],
  [/\b(onboard)\b/i, Compass],
  [/\b(optimize|performance)\b/i, Gauge],
  [/\b(overdrive|prototype)\b/i, FlaskConical],
  [/\b(to-prd|to-issues|autoplan|plan-|plan_)\b/i, ListChecks],
  [/\b(scaffold-exercises)\b/i, GraduationCap],
  [/\b(pre-commit|git)\b/i, GitCommit],
  [/\b(tdd|test)\b/i, TestTube],
  [/\b(zoom-out|research)\b/i, Telescope],
  [/\b(ship|release)\b/i, Rocket],
  [/\b(retro|history)\b/i, History],
  [/\b(cso|ceo|strategy)\b/i, BrainCircuit],
  [/\b(para-memory|memory-files)\b/i, BrainCircuit],
  [/\b(paperclip)\b/i, ClipboardCheck],
  [/\b(extract|component|blocks)\b/i, Boxes],
  [/\b(polish|delight)\b/i, Sparkles],
  [/\b(distill|caveman)\b/i, PenLine],
  [/\b(setup|find-skills|skill-creator|writing-skills)\b/i, Wrench],
  [/\b(code|frontend|typescript|react)\b/i, Code],
];

export function resolveSkillCatalogIcon(
  identity: string,
  name = '',
  kind: 'skill' | 'market' = 'skill',
): LucideIcon {
  const searchableIdentity = `${identity} ${name}`;
  const match = SKILL_ICON_RULES.find(([pattern]) => pattern.test(searchableIdentity));
  return match?.[1] ?? (kind === 'market' ? Package : Puzzle);
}
